Language="VBSCRIPT"

Sub CATMain()
    Dim mainDirectory as String
    mainDirectory = "G:\CTS\junk\0Ufunc Testing\Project_Estimating"

    Dim translateDirectory As String
    translateDirectory = mainDirectory & "\TSG - Translated Data"

    Dim suppliedDirectory As String
    suppliedDirectory = mainDirectory & "\Supplied Cad Data"

    Dim photosDirectory As String
    photosDirectory = mainDirectory & "\Photos"


    ' FileSystemObject.CopyFile "C:\Catia\Project_Estimating\CAD Info.xlsx", mainDirectory & "\CAD Info.xlsx"


    Set objFSO = Createobject("Scripting.FileSystemObject")

    objFSO.CreateFolder(translateDirectory)
    objFSO.CreateFolder(suppliedDirectory)
    objFSO.CreateFolder(photosDirectory)
    objFSO.CopyFile "C:\Catia\Project_Estimating\CAD Info.xlsx", mainDirectory & "\CAD Info.xlsx"


    Dim myExcel As Microsoft.Office.Interop.Excel.Application

    Set myExcel = CreateObject("Excel.Application")
    myExcel.Workbooks.Open(mainDirectory & "\CAD Info.xlsx")
    Dim myWorkbook As Microsoft.Office.Interop.Excel.Workbook
    Set myWorkbook = myExcel.Workbooks.Item(1)
    myWorkbook.Activate()
    myWorkbook.Sheets(1).Select()
    Set myWorksheet = myWorkbook.ActiveSheet
    myWorksheet.Columns("B:B").ColumnWidth = 20
    'myExcel.Visible = True
    Dim iRow As Integer
    iRow = 2

    Set oFolder = objFSO.GetFolder(mainDirectory)
    For Each oFile in oFolder.Files

        Dim dataPath As String
        dataPath = oFile

        Dim fileName as String
        fileName = LCase(oFile.Name)

        Dim dotIndex As Integer
        dotIndex = InStrRev(fileName,".")

        Dim dataExtension As String
        dataExtension = LCase(Mid(fileName, dotIndex))

        Dim fileLeaf As String
        fileLeaf = LCase(Left(fileName,dotIndex - 1))

        Dim catPath as String
        catPath = mainDirectory & "\" & fileLeaf & ".catpart"

        Dim igsPath As String
        igsPath = mainDirectory & "\" & fileLeaf & ".igs"

        Dim stpPath As String
        stpPath = mainDirectory & "\" & fileLeaf & ".stp"

        Select Case dataExtension
         Case ".catpart"
            CATIA.Documents.Open(dataPath)

            CATIA.ActiveWindow.ActiveViewer.Reframe

            CATIA.ActiveDocument.ExportData translateDirectory & "\" & fileLeaf & ".igs", "igs"

            CATIA.ActiveDocument.ExportData translateDirectory & "\" & fileLeaf & ".stp", "stp"

            CATIA.ActiveWindow.ActiveViewer.CaptureToFile catCaptureFormatBMP, photosDirectory & "\" & fileLeaf & ".bmp"

            myWorksheet.Cells(iRow, 18).RowHeight = 80

            myWorksheet.Cells(iRow, 18).Value  = fileLeaf & ".bmp"


            ' Dim mainBody As Body
            ' Set mainBody = CATIA.ActiveDocument.Part.MainBody

            ' ' Dim theHSF As HybridShapeTypeLib.HybridShapeFactory
            ' ' theHSF = mainBody.HybridShapeFactory

            ' ' Dim body As Body
            ' ' Set body = CATIA.ActiveDocument.Part.Bodies.MainBody
            ' Dim hybridBodyColl As HybridBodies
            ' hybridBodyColl = mainBody.HybridBodies

            ' MsgBox "hello" & hybridBodyColl.Count




            CATIA.ActiveWindow.Close()

            objFSO.MoveFile oFile, suppliedDirectory & "\" & fileLeaf & dataExtension

            iRow = iRow + 1
         Case ".stp"
            CATIA.Documents.Open(dataPath)

            CATIA.ActiveWindow.ActiveViewer.Reframe

            CATIA.ActiveDocument.SaveAs translateDirectory & "\" & fileLeaf & ".catpart"

            CATIA.ActiveWindow.ActiveViewer.CaptureToFile catCaptureFormatBMP, photosDirectory & "\" & fileLeaf & ".bmp"

            CATIA.ActiveDocument.ExportData translateDirectory & "\" & fileLeaf & ".igs", "igs"

            CATIA.ActiveWindow.Close()

            objFSO.MoveFile oFile, suppliedDirectory & "\" & fileLeaf & dataExtension

            myWorksheet.Cells(iRow, 18).RowHeight = 80

            myWorksheet.Cells(iRow, 18).Value  = fileLeaf & ".bmp"

            iRow = iRow + 1



         Case ".igs"
            CATIA.Documents.Open(dataPath)

            CATIA.ActiveWindow.ActiveViewer.Reframe

            CATIA.ActiveDocument.SaveAs translateDirectory & "\" & fileLeaf & ".catpart"

            CATIA.ActiveWindow.ActiveViewer.CaptureToFile catCaptureFormatBMP, photosDirectory & "\" & fileLeaf & ".bmp"

            CATIA.ActiveDocument.ExportData translateDirectory & "\" & fileLeaf & ".stp", "stp"

            CATIA.ActiveWindow.Close()

            objFSO.MoveFile oFile, suppliedDirectory & "\" & fileLeaf & dataExtension

            myWorksheet.Cells(iRow, 18).RowHeight = 80

            myWorksheet.Cells(iRow, 18).Value  = fileLeaf & ".bmp"

            iRow = iRow + 1


         Case Else
            MsgBox "Unknown extension: '" & dataExtension & "'"

        End Select


        Next


        myWorkbook.Save()
        myExcel.Quit()
        myExcel.Quit()

End Sub
